name: dimovie_final_expert_project
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  provider: ^6.0.3
  http: ^0.13.3
  get_it: ^7.1.3
  flutter:
    sdk: flutter
  module_common:
    path: module_common
  module_movies:
    path: module_movies
  module_tvseries:
    path: module_tvseries

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
 


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  